name = "MultivariateOnlineStatistics"
uuid = "e9d32067-d496-40b5-8c90-e40f06d38009"
authors = ["Éric Thiébaut <eric.thiebaut@univ-lyon1.fr>"]
version = "0.1.0"

[deps]
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[compat]
julia = "1.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
